from __future__ import annotations

from enum import Enum
from pathlib import Path
from uuid import uuid4
from typing import Any

from pydantic import BaseModel, Field

INGESTION_SCHEMA_VERSION = "2.0.0"


class StructuralClass(str, Enum):
    STRUCTURED = "structured"
    SEMI_STRUCTURED = "semi_structured"
    UNSTRUCTURED = "unstructured"
    BINARY = "binary"


class ColumnDefinition(BaseModel):
    name: str
    sql_type: str = "TEXT"
    description: str = ""
    nullable: bool = True
    primary_key: bool = False


class TableDefinition(BaseModel):
    table_name: str
    display_name: str = ""
    columns: list[ColumnDefinition]
    ddl: str


class ParserPipelineResult(BaseModel):
    table_definitions: list[TableDefinition]
    records: dict[str, list[dict[str, Any]]]
    parser_key: str
    warnings: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0, default=1.0)
    diagnostics: dict[str, Any] = Field(default_factory=dict)

    @property
    def row_counts(self) -> dict[str, int]:
        return {table_name: len(rows) for table_name, rows in self.records.items()}


class FileClassification(BaseModel):
    file_id: str | None = None
    filename: str
    detected_format: str
    structural_class: StructuralClass
    format_confidence: float = Field(ge=0.0, le=1.0)
    line_count: int
    warnings: list[str] = Field(default_factory=list)


class ClassificationResult(BaseModel):
    schema_version: str = INGESTION_SCHEMA_VERSION
    dominant_format: str
    structural_class: StructuralClass
    selected_parser_key: str
    file_classifications: list[FileClassification]
    warnings: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0, default=1.0)
    diagnostics: dict[str, Any] = Field(default_factory=dict)


class ParserSupportRequest(BaseModel):
    file_id: str | None = None
    filename: str
    content: str
    mime_type: str | None = None


class ParserSupportResult(BaseModel):
    parser_key: str
    supported: bool
    score: float = Field(ge=0.0, le=1.0, default=0.0)
    reasons: list[str] = Field(default_factory=list)
    detected_format: str | None = None
    structural_class: StructuralClass | None = None


class FileParserSelection(BaseModel):
    file_id: str | None = None
    filename: str
    parser_key: str
    score: float = Field(ge=0.0, le=1.0)
    reasons: list[str] = Field(default_factory=list)


BASELINE_COLUMNS: list[ColumnDefinition] = [
    ColumnDefinition(
        name="id",
        sql_type="INTEGER",
        nullable=False,
        primary_key=True,
        description="Auto-incrementing primary key.",
    ),
    ColumnDefinition(
        name="timestamp",
        sql_type="TEXT",
        description="Normalized ISO-8601 timestamp, if detectable.",
    ),
    ColumnDefinition(
        name="raw",
        sql_type="TEXT",
        nullable=False,
        description="Complete original log text.",
    ),
    ColumnDefinition(
        name="extra",
        sql_type="TEXT",
        description="JSON blob for data that cannot be represented as columns.",
    ),
]

BASELINE_COLUMN_NAMES: frozenset[str] = frozenset(column.name for column in BASELINE_COLUMNS)


def _quote_identifier(name: str) -> str:
    escaped = name.replace('"', '""')
    return f'"{escaped}"'


def build_ddl(table_name: str, columns: list[ColumnDefinition]) -> str:
    safe_table = _quote_identifier(table_name)
    column_definitions: list[str] = []

    for column in columns:
        safe_name = _quote_identifier(column.name)
        parts = [safe_name, column.sql_type]
        if column.primary_key:
            if column.sql_type.upper() in {"INTEGER", "INT", "BIGINT"}:
                parts = [safe_name, "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"]
            else:
                parts.append("PRIMARY KEY")
        if not column.nullable and not column.primary_key:
            parts.append("NOT NULL")
        column_definitions.append("    " + " ".join(parts))

    columns_sql = ",\n".join(column_definitions)
    return f"CREATE TABLE IF NOT EXISTS {safe_table} (\n{columns_sql}\n);"


def make_display_name(parser_key: str, file_id: str | None, filename: str) -> str:
    base_name = Path(filename).stem
    if ":" in base_name:
        base_name = base_name.split(":")[-1]
    
    name_parts = [part for part in [base_name, parser_key] if part]
    combined = " ".join(name_parts)
    return combined.replace("_", " ").title()


def make_megabase_table_name() -> str:
    return str(uuid4())
